-- Список участников турнира (bulk-add по никам в админке). Позволяет показать каркас
-- сетки с реальными именами по сеянию ещё до того, как заведены встречи (encounters).
-- seed : посев (1..N) — порядок в сетке; NULL = без посева (добавится в конец).
create table if not exists tournament_participants (
  id            bigint generated by default as identity primary key,
  tournament_id uuid not null references tournaments(id) on delete cascade,
  player_id     uuid not null references players(id) on delete cascade,
  seed          int,
  created_at    timestamptz default now(),
  unique (tournament_id, player_id)
);
alter table tournament_participants enable row level security;
create policy "participants read"  on tournament_participants for select using (true);
create policy "participants write" on tournament_participants for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
